services:
  - type: web
    name: umbrella-task-manager
    env: node
    buildCommand: cd server && npm install && npm run build && cd ../client && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false 